### PR TITLE
PCBS micro-benchmark

### PR DESCRIPTION
**Pull request by razajafri**
This is micro-benchmark used to compare performance of writing/reading cached batches using PCBS and DefaultCachedBatchSerializer

### CODE REVIEW

**Comment by razajafri** [comment]
@viadea

File: examples/pcbs-benchmark/src/main/scala/org/apache/spark/sql/execution/columnar/Util.scala [hunk 1]
```diff
@@ -0,0 +1,244 @@
...
+ * @author Raza Jafri
+ */
+object Util {
+  def createSparkSession(): SparkSession = {
+    // Timezone is fixed to UTC to allow timestamps to work by default
+    TimeZone.setDefault(TimeZone.getTimeZone("UTC"))
+    // Add Locale setting
+    Locale.setDefault(Locale.US)
+    val builder = SparkSession.builder()
+        .master("spark://raza-linux-2:7077")
```
Comment (nvliyuan) [inline examples/pcbs-benchmark/src/main/scala/org/apache/spark/sql/execution/columnar/Util.scala:91]: can we make the configs variables? It is better if we can update the params in pcbs-benchmark.sh script

File: examples/pcbs-benchmark/pcbs-benchmark.sh [hunk 2]
```diff
@@ -0,0 +1,82 @@
...
+--conf spark.rapids.sql.castStringToInteger.enabled=true \
+--conf spark.driver.extraJavaOptions='-ea -Duser.timezone=UTC' \
+--conf spark.executor.extraJavaOptions='-ea -Duser.timezone=UTC -Dai.rapids.cudf.prefer-pinned=true' \
+--conf spark.task.resource.gpu.amount=0.08 \
+--conf spark.executor.resource.gpu.amount=1 \
+--conf spark.rapids.shuffle.ucx.enabled=false \
+--conf spark.rapids.sql.explain=ALL \
+--conf spark.rapids.sql.decimalType.enabled=true \
+--conf spark.sql.parquet.filterPushdown=true \
+--conf spark.executor.resource.gpu.discoveryScript=./getGpusResources.sh \
```
Comment (nvliyuan) [inline examples/pcbs-benchmark/pcbs-benchmark.sh:78]: I don't find getGpusResources.sh in the repo, should this be updated to ${SPARK_HOME}/examples/src/main/scripts/getGpusResources.sh ?

**Comment by nvliyuan** [comment]
I spend some time building the jar, due to the terrible urm or maven repository network. Shall we add more comments to guide customers to download and install mvn package manually to save times? Such as
```
wget https://XXX/rapids-4-spark_2.12-22.06.0-20220512.134355-33-cuda11.jar

mvn install:install-file -DcreateChecksum=true -Dpackaging=jar -DgroupId=com.nvidia -DartifactId=rapids-4-spark_2.12 -Dversion=22.06.0-SNAPSHOT -Dclassifier=cuda11 -Dfile=/your-path/rapids-4-spark_2.12-22.06.0-20220512.134355-33-cuda11.jar
```

**Comment by nvliyuan** [comment]
Do we need to add some sample datasets under ```datasets``` folder?  What are the considerations about parquet file when we test? For example， how does the parquet file size influence the performance.

File: examples/pcbs-benchmark/pcbs-benchmark.sh [hunk 3]
```diff
@@ -0,0 +1,82 @@
+BENCH_JAR="/home/rjafri/spark-rapids-examples/examples/pcbs-benchmark/target/pcbs-benchmark-1.0-SNAPSHOT.jar"
```
Comment (nvliyuan) [inline examples/pcbs-benchmark/pcbs-benchmark.sh:1]: maybe we should hide personal information from path

File: examples/pcbs-benchmark/pcbs-benchmark.sh (hunk 2 above)
Comment (razajafri) [reply examples/pcbs-benchmark/pcbs-benchmark.sh:78]: The file will be shipped from SPARK_HOME to each executor AFAIK

File: examples/pcbs-benchmark/src/main/scala/org/apache/spark/sql/execution/columnar/Util.scala (hunk 1 above)
Comment (razajafri) [reply examples/pcbs-benchmark/src/main/scala/org/apache/spark/sql/execution/columnar/Util.scala:91]: I have removed the settings from here. 

> I spend some time building the jar, due to the terrible urm or maven repository network. Shall we add more comments to guide customers to download and install mvn package manually to save time? Such as
> 
> ```
> wget https://XXX/rapids-4-spark_2.12-22.06.0-20220512.134355-33-cuda11.jar
> 
> mvn install:install-file -DcreateChecksum=true -Dpackaging=jar -DgroupId=com.nvidia -DartifactId=rapids-4-spark_2.12 -Dversion=22.06.0-SNAPSHOT -Dclassifier=cuda11 -Dfile=/your-path/rapids-4-spark_2.12-22.06.0-20220512.134355-33-cuda11.jar
> ```

This is not necessary I think because the file can be built locally or downloaded however the user wants and put in the `lib` folder

**Comment by razajafri** [comment]
> I spend some time building the jar, due to the terrible urm or maven repository network. Shall we add more comments to guide customers to download and install mvn package manually to save time? Such as
> 
> ```
> wget https://XXX/rapids-4-spark_2.12-22.06.0-20220512.134355-33-cuda11.jar
> 
> mvn install:install-file -DcreateChecksum=true -Dpackaging=jar -DgroupId=com.nvidia -DartifactId=rapids-4-spark_2.12 -Dversion=22.06.0-SNAPSHOT -Dclassifier=cuda11 -Dfile=/your-path/rapids-4-spark_2.12-22.06.0-20220512.134355-33-cuda11.jar
> ```

This is not necessary I think because the file can be built locally or downloaded however the user wants and put in the `lib` folder

**Comment by razajafri** [comment]
> Do we need to add some sample datasets under `datasets` folder? What are the considerations about parquet file when we test? For example， how does the parquet file size influence the performance.

I think the data is publicly available and unnecessary to push into the repo. The files are huge

File: examples/pcbs-benchmark/README.md [hunk 4]
```diff
@@ -0,0 +1,94 @@
...
+sbin/start-master.sh 
+sbin/start-slave.sh <master-url>
+```
+
+## Run the benchmark
+
+The benchmark can be run by running the script file and passing the name of parquet file to be read and cached e.g.
+
+```
+./pcbs-benchmark.sh /media/rjafri/data/data/mortgage_parquet/20m
```
Comment (sameerz) [inline examples/pcbs-benchmark/README.md:34]: Are there instructions on how to download the data? 

Also, another instance where we can remove the user name.

File: examples/pcbs-benchmark/pcbs-benchmark.sh [hunk 5]
```diff
@@ -0,0 +1,106 @@
...
+PLUGIN_JAR="lib/rapids-4-spark_2.12-22.06.0-20220512.134355-33-cuda11.jar"
+SPARK_HOME="/home/rjafri/spark-3.1.1-bin-hadoop3.2"
+
+DRIVE_MEMORY=32 # GB
+SPARK_RAPIDS_MEMORY_PINNEDPOOL_SIZE=16 #GB
+EXECUTOR_MEMORY=32 # GB
+EXECUTOR_CORES=16 
+NUM_EXECUTOR=4
+
+SPARK_TASK_CPUS=1
```
Comment (sameerz) [inline examples/pcbs-benchmark/pcbs-benchmark.sh:11]: Why so many configs?  Especially when some of these are set to the default values?

File: examples/pcbs-benchmark/pcbs-benchmark.sh [hunk 6]
```diff
@@ -0,0 +1,106 @@
...
+SPARK_SQL_SHUFFLE.PARTITIONS=200
+SPARK_SQL_FILES_MAXPARTITIONBYTES=1024
+SPARK_DYNAMICALLOCATION_ENABLED=false
+SPARK_PLUGINS="com.nvidia.spark.SQLPlugin"
+SPARK_RAPIDS_SQL_INCOMPATIBLEOPS_ENABLED="true"
+SPARK_RAPIDS_SQL_VARIABLEFLOATAGG_ENABLED="true"
+SPARK_RAPIDS_SQL_CONCURRENTGPUTASKS=4
+SPARK_SQL_INMEMORYCOLUMNARSTORAGE_COMPRESSED="true"
+SPARK_SQL_ADAPTIVE_ENABLED="true"
+SPARK_RAPIDS_MEMORY_GPU_POOL="ARENA"
```
Comment (sameerz) [inline examples/pcbs-benchmark/pcbs-benchmark.sh:24]: Is ARENA necessary for this microbenchmark?

File: examples/pcbs-benchmark/src/main/scala/com/nvidia/CachePerfWriter.scala [hunk 7]
```diff
@@ -0,0 +1,46 @@
...
+ * See the License for the specific language governing permissions and
+ * limitations under the License.
+ */
+package com.nvidia
+
+import java.io.{BufferedWriter, File, FileWriter, IOException}
+
+/**
+ * @author Raza Jafri
+ */
```
Comment (sameerz) [inline examples/pcbs-benchmark/src/main/scala/com/nvidia/CachePerfWriter.scala:22]: Not necessary (do we have other submissions with developer names in the files?)

**Review by sameerz — CHANGES_REQUESTED** [review]

File: examples/pcbs-benchmark/pcbs-benchmark.sh [hunk 8]
```diff
@@ -0,0 +1,106 @@
...
+SPARK_TASK_CPUS=1
+SPARK_DRIVER_MAXRESULTSIZE=0
+SPARK_LOCALITY_WAIT=0
+SPARK_EXECUTOR_HEARTBEATINTERVAL=20
+SPARK_SQL_SHUFFLE.PARTITIONS=200
+SPARK_SQL_FILES_MAXPARTITIONBYTES=1024
+SPARK_DYNAMICALLOCATION_ENABLED=false
+SPARK_PLUGINS="com.nvidia.spark.SQLPlugin"
+SPARK_RAPIDS_SQL_INCOMPATIBLEOPS_ENABLED="true"
+SPARK_RAPIDS_SQL_VARIABLEFLOATAGG_ENABLED="true"
```
Comment (sameerz) [inline examples/pcbs-benchmark/pcbs-benchmark.sh:20]: Are these being removed in 22.06/

**Review by sameerz — CHANGES_REQUESTED** [review]

File: examples/pcbs-benchmark/README.md (hunk 4 above)
Comment (razajafri) [reply examples/pcbs-benchmark/README.md:34]: This isn't targeting any specific data. We can use any data we want. I can remove the username

File: examples/pcbs-benchmark/pcbs-benchmark.sh (hunk 6 above)
Comment (razajafri) [reply examples/pcbs-benchmark/pcbs-benchmark.sh:24]: I didn't play around with this setting, I asked in one of the standups and the impression I have is that we don't want to change this. Please correct me if I am wrong

File: examples/pcbs-benchmark/pcbs-benchmark.sh (hunk 8 above)
Comment (razajafri) [reply examples/pcbs-benchmark/pcbs-benchmark.sh:20]: Yes, they are. I wasn't sure if we should remove them now or after the release

File: examples/pcbs-benchmark/src/main/scala/com/nvidia/CachePerfWriter.scala (hunk 7 above)
Comment (razajafri) [reply examples/pcbs-benchmark/src/main/scala/com/nvidia/CachePerfWriter.scala:22]: This is my IDE's default behavior when I create new classes. I am not sure if we have other submissions, but I am not that particular about keeping my name in the file :smile:  I will remove it.

File: examples/pcbs-benchmark/pcbs-benchmark.sh (hunk 5 above)
Comment (razajafri) [reply examples/pcbs-benchmark/pcbs-benchmark.sh:11]: The default values could change in future which is why I set them.

File: examples/pcbs-benchmark/benchmark-multiple-files.sh [hunk 9]
```diff
@@ -0,0 +1,22 @@
+# File path for the files
+FILE_PREFIX="/media/rjafri/data/data/mortgage_parquet/"
```
Comment (nvliyuan) [inline examples/pcbs-benchmark/benchmark-multiple-files.sh:2]: can you please update the path to remove the name?

File: examples/pcbs-benchmark/pcbs-benchmark.sh [hunk 10]
```diff
@@ -0,0 +1,106 @@
+BENCH_JAR="/home/rjafri/spark-rapids-examples/examples/pcbs-benchmark/target/pcbs-benchmark-1.0-SNAPSHOT.jar"
+PLUGIN_JAR="lib/rapids-4-spark_2.12-22.06.0-20220512.134355-33-cuda11.jar"
+SPARK_HOME="/home/rjafri/spark-3.1.1-bin-hadoop3.2"
```
Comment (nvliyuan) [inline examples/pcbs-benchmark/pcbs-benchmark.sh:3]: same here.

File: examples/pcbs-benchmark/pcbs-benchmark.sh [hunk 11]
```diff
@@ -0,0 +1,106 @@
...
+SPARK_RAPIDS_SQL_VARIABLEFLOATAGG_ENABLED="true"
+SPARK_RAPIDS_SQL_CONCURRENTGPUTASKS=4
+SPARK_SQL_INMEMORYCOLUMNARSTORAGE_COMPRESSED="true"
+SPARK_SQL_ADAPTIVE_ENABLED="true"
+SPARK_RAPIDS_MEMORY_GPU_POOL="ARENA"
+SPARK_RAPIDS_MEMORY_GPU_ALLOCFRACTION=0.9
+SPARK_RAPIDS_SQL_CASTSTRINGTOINTEGER_ENABLED="true"
+SPARK_DRIVER_EXTRAJAVAOPTIONS="-ea -Duser.timezone=UTC"
+SPARK_EXECUTOR_EXTRAJAVAOPTIONS="-ea -Duser.timezone=UTC -Dai.rapids.cudf.prefer-pinned=true"
+SPARK_TASK_RESOURCE_GPU_AMOUNT=0.8
```
Comment (nvliyuan) [inline examples/pcbs-benchmark/pcbs-benchmark.sh:29]: can you please update the config to 1/cpu-core? otherwise we could get
```will result in wasted resources due to resource gpu limiting the number of runnable tasks per executor``` or 
```will result in wasted resources due to resource cpus limiting the number of runnable tasks per executor to``` warning

File: examples/pcbs-benchmark/pcbs-benchmark.sh [hunk 12]
```diff
@@ -0,0 +1,106 @@
...
+SPARK_RAPIDS_MEMORY_PINNEDPOOL_SIZE=16 #GB
+EXECUTOR_MEMORY=32 # GB
+EXECUTOR_CORES=16 
+NUM_EXECUTOR=4
+
+SPARK_TASK_CPUS=1
+SPARK_DRIVER_MAXRESULTSIZE=0
+SPARK_LOCALITY_WAIT=0
+SPARK_EXECUTOR_HEARTBEATINTERVAL=20
+SPARK_SQL_SHUFFLE.PARTITIONS=200
```
Comment (nvliyuan) [inline examples/pcbs-benchmark/pcbs-benchmark.sh:15]: a typo here, should update to `SPARK_SQL_SHUFFLE_PARTITIONS`

File: examples/pcbs-benchmark/pcbs-benchmark.sh [hunk 13]
```diff
@@ -0,0 +1,106 @@
...
+--conf spark.rapids.sql.incompatibleOps.enabled=${SPARK_RAPIDS_SQL_INCOMPATIBLEOPS_ENABLED} \
+--conf spark.rapids.sql.variableFloatAgg.enabled=${SPARK_RAPIDS_SQL_VARIABLEFLOATAGG_ENABLED} \
+--conf spark.rapids.sql.concurrentGpuTasks=${CONCURRENT_GPU_TASKS} \
+--conf spark.sql.inMemoryColumnarStorage.compressed=${SPARK_SQL_INMEMORYCOLUMNARSTORAGE_COMPRESSED} \
+--conf spark.sql.adaptive.enabled=${SPARK_SQL_ADAPTIVE_ENABLED} \
+--conf spark.rapids.memory.gpu.pool=${SPARK_RAPIDS_MEMORY_GPU_POOL} \
+--conf spark.rapids.memory.pinnedPool.size=${SPARK_RAPIDS_MEMORY_PINNEDPOOL_SIZE}G \
+--conf spark.rapids.memory.gpu.allocFraction=${SPARK_RAPIDS_MEMORY_GPU_ALLOCFRACTION} \
+--conf spark.rapids.sql.castStringToInteger.enabled=${SPARK_RAPIDS_SQL_CASTSTRINGTOINTEGER_ENABLED} \
+--conf spark.driver.extraJavaOptions=${SPARK_DRIVER_EXTRAJAVAOPTIONS} \
```
Comment (nvliyuan) [inline examples/pcbs-benchmark/pcbs-benchmark.sh:59]: seems we need to update to 
` --conf spark.driver.extraJavaOptions="-ea -Duser.timezone=UTC" \
--conf spark.executor.extraJavaOptions="-ea -Duser.timezone=UTC -Dai.rapids.cudf.prefer-pinned=true" \ `
 otherwise we could get error `Error: Unrecognized option: -Duser.timezone=UTC`

File: examples/pcbs-benchmark/pcbs-benchmark.sh [hunk 14]
```diff
@@ -0,0 +1,106 @@
...
+--conf spark.driver.maxResultSize=${SPARK_DRIVER_MAXRESULTSIZE} \
+--conf spark.locality.wait=${SPARK_LOCALITY_WAIT} \
+--conf spark.executor.heartbeatInterval=${SPARK_EXECUTOR_HEARTBEATINTERVAL}s \
+--conf spark.sql.shuffle.partitions=${SPARK_SQL_SHUFFLE_PARTITIONS} \
+--conf spark.sql.files.maxPartitionBytes=${SPARK_SQL_FILES_MAXPARTITIONBYTES}m \
+--conf spark.dynamicAllocation.enabled=${SPARK_DYNAMICALLOCATION_ENABLED} \
+--conf spark.plugins=${SPARK_PLUGINS} \
+--conf spark.rapids.sql.incompatibleOps.enabled=${SPARK_RAPIDS_SQL_INCOMPATIBLEOPS_ENABLED} \
+--conf spark.rapids.sql.variableFloatAgg.enabled=${SPARK_RAPIDS_SQL_VARIABLEFLOATAGG_ENABLED} \
+--conf spark.rapids.sql.concurrentGpuTasks=${CONCURRENT_GPU_TASKS} \
```
Comment (nvliyuan) [inline examples/pcbs-benchmark/pcbs-benchmark.sh:88]: seems typo here, need to update to `SPARK_RAPIDS_SQL_CONCURRENTGPUTASKS`

File: examples/pcbs-benchmark/pcbs-benchmark.sh [hunk 15]
```diff
@@ -0,0 +1,106 @@
...
```
Comment (nvliyuan) [inline examples/pcbs-benchmark/pcbs-benchmark.sh:52]: same typo , `SPARK_RAPIDS_SQL_CONCURRENTGPUTASKS`

**Comment by nvliyuan** [comment]
@razajafri is the demo specific to spark3.1.X?  it works well with spark 3.1.1 and 3.1.2, but failed with spark3.2.0 due to spark version mismatch
```Exception in thread "main" java.lang.NoSuchMethodError: org.apache.spark.sql.internal.SessionState.executePlan(Lorg/apache/spark/sql/catalyst/plans/logical/LogicalPlan;)Lorg/apache/spark/sql/execution/QueryExecution;
  at org.apache.spark.sql.execution.columnar.Util$.$anonfun$readWriteCache$1(Util.scala:98)
  at scala.runtime.java8.JFunction1$mcJI$sp.apply(JFunction1$mcJI$sp.java:23)
  at scala.collection.TraversableLike.$anonfun$map$1(TraversableLike.scala:286)
  at scala.collection.immutable.Range.foreach(Range.scala:158)
  at scala.collection.TraversableLike.map(TraversableLike.scala:286)
  at scala.collection.TraversableLike.map$(TraversableLike.scala:279)
  at scala.collection.AbstractTraversable.map(Traversable.scala:108)
  at org.apache.spark.sql.execution.columnar.Util$.readWriteCache(Util.scala:95)
  at org.apache.spark.sql.execution.columnar.Util$.runPcbsInternal(Util.scala:184)
  at org.apache.spark.sql.execution.columnar.Util$.runPcbs(Util.scala:190)
  at com.nvidia.BenchmarkPcbs$.main(RunPCBS.scala:28)
  at com.nvidia.BenchmarkPcbs.main(RunPCBS.scala)
  at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
  at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
  at java.lang.reflect.Method.invoke(Method.java:498)```

**Comment by nvliyuan** [comment]
@razajafri can you please also make the spark master URL a variable?
such as `${BENCH_JAR} $url $data-path` in pcbs-benchmark.sh, then we don't need to hardcode in Util.scala
`.master("spark://raza-linux-2:7077")`

**Comment by razajafri** [comment]
> @razajafri is the demo specific to spark3.1.X? it works well with spark 3.1.1 and 3.1.2, but failed with spark3.2.0 due to spark version mismatch
> 
> ```
> Exception in thread "main" java.lang.NoSuchMethodError: org.apache.spark.sql.internal.SessionState.executePlan(Lorg/apache/spark/sql/catalyst/plans/logical/LogicalPlan;)Lorg/apache/spark/sql/execution/QueryExecution;
>   at org.apache.spark.sql.execution.columnar.Util$.$anonfun$readWriteCache$1(Util.scala:98)
>   at scala.runtime.java8.JFunction1$mcJI$sp.apply(JFunction1$mcJI$sp.java:23)
>   at scala.collection.TraversableLike.$anonfun$map$1(TraversableLike.scala:286)
>   at scala.collection.immutable.Range.foreach(Range.scala:158)
>   at scala.collection.TraversableLike.map(TraversableLike.scala:286)
>   at scala.collection.TraversableLike.map$(TraversableLike.scala:279)
>   at scala.collection.AbstractTraversable.map(Traversable.scala:108)
>   at org.apache.spark.sql.execution.columnar.Util$.readWriteCache(Util.scala:95)
>   at org.apache.spark.sql.execution.columnar.Util$.runPcbsInternal(Util.scala:184)
>   at org.apache.spark.sql.execution.columnar.Util$.runPcbs(Util.scala:190)
>   at com.nvidia.BenchmarkPcbs$.main(RunPCBS.scala:28)
>   at com.nvidia.BenchmarkPcbs.main(RunPCBS.scala)
>   at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
>   at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
>   at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
>   at java.lang.reflect.Method.invoke(Method.java:498)```
> ```

Yes, the benchmark was run on Spark 3.1.1 and it's very specific to it for now. We can in future make changes to it

File: examples/pcbs-benchmark/pcbs-benchmark.sh (hunk 13 above)
Comment (razajafri) [reply examples/pcbs-benchmark/pcbs-benchmark.sh:59]: fixed the problem by putting the variable in quotes

File: examples/pcbs-benchmark/pcbs-benchmark.sh (hunk 11 above)
Comment (razajafri) [reply examples/pcbs-benchmark/pcbs-benchmark.sh:29]: What's the advantage of doing that? The user will still have to modify the variable cpu-core. Bash doesn't do floating-point arithmetic and I will have to rely on another util with no real benefit.

**Comment by razajafri** [comment]
@nvliyuan I think I have addressed your concerns. PTAL

File: examples/pcbs-benchmark/pcbs-benchmark.sh (hunk 11 above)
Comment (nvliyuan) [reply examples/pcbs-benchmark/pcbs-benchmark.sh:28]: agree, users will update that. But I assume that not all customers are familiar with this config, and during the test, I failed with error 
```
java.lang.AssertionError: assertion failed: The resource amount 0.8 must be either <= 0.5, or a whole number.
	at scala.Predef$.assert(Predef.scala:223)
	at org.apache.spark.resource.TaskResourceRequest.<init>(TaskResourceRequest.scala:41)
	at org.apache.spark.resource.TaskResourceRequests.resource(TaskResourceRequests.scala:72)
	at org.apache.spark.resource.ResourceUtils$.$anonfun$addTaskResourceRequests$1(ResourceUtils.scala:198)
	at scala.collection.TraversableLike.$anonfun$map$1(TraversableLike.scala:238)
```
so not sure shall we add a comment [link](https://nvidia.github.io/spark-rapids/docs/tuning-guide.html#number-of-tasks-per-executor) to guide customers to set a right number to avoid failure

File: examples/pcbs-benchmark/src/main/scala/com/nvidia/CachePerfWriter.scala [hunk 16]
```diff
@@ -0,0 +1,43 @@
...
+  }
+
+  def appendTimes(
+      acc: Boolean,
+      write: Long,
+      firstRead: Long,
+      readAvg: Long): Unit ={
+    appendLine(s"acc: $acc")
+    appendLine("Average write: " + write)
+    appendLine("Time taken for frst read: " + firstRead)
```
Comment (nvliyuan) [inline examples/pcbs-benchmark/src/main/scala/com/nvidia/CachePerfWriter.scala:36]: frst -> first

**Comment by nvliyuan** [comment]
this is the perf result I get:
```
*****
PCBS
acc: true
Average write: 585
Time taken for frst read: 361
Average read (without first read): 142
acc: false
Average write: 3399
Time taken for frst read: 3619
Average read (without first read): 370
*******
DefaultSerializer
acc: true
Average write: 1429
Time taken for frst read: 946
Average read (without first read): 73
acc: false
Average write: 1298
Time taken for frst read: 1133
Average read (without first read): 54
```
Can I make a conclusion that if we enable PCBS(GpuInMemoryTableScanExec), we could get 5.8x(3399/585) speedups in ParquetCachedBatch write and 2.6x(370/1422) speedups in ParquetCachedBatch read if we enable the rapids plugin? And if we don't enable PCBS(GpuInMemoryTableScanExec),  there is no difference whether we enable rapids plugin?

File: examples/pcbs-benchmark/README.md [hunk 17]
```diff
@@ -0,0 +1,93 @@
...
+sbin/start-master.sh 
+sbin/start-slave.sh <master-url>
+```
+
+## Run the benchmark
+
+The benchmark can be run by running the script file and passing the name of Parquet file to be read and cached e.g.
+
+```
+./pcbs-benchmark.sh <path to Parquet file>
```
Comment (nvliyuan) [inline examples/pcbs-benchmark/README.md:34]: since we updated the scripts, maybe also need to update the README.md doc

File: examples/pcbs-benchmark/pcbs-benchmark.sh (hunk 13 above)
Comment (nvliyuan) [reply examples/pcbs-benchmark/pcbs-benchmark.sh]: thanks, that also works

**Comment by razajafri** [comment]
> this is the perf result I get:
> 
> ```
> *****
> PCBS
> acc: true
> Average write: 585
> Time taken for frst read: 361
> Average read (without first read): 142
> acc: false
> Average write: 3399
> Time taken for frst read: 3619
> Average read (without first read): 370
> *******
> DefaultSerializer
> acc: true
> Average write: 1429
> Time taken for frst read: 946
> Average read (without first read): 73
> acc: false
> Average write: 1298
> Time taken for frst read: 1133
> Average read (without first read): 54
> ```
> 
> Can I make a conclusion that if we enable PCBS(GpuInMemoryTableScanExec), we could get 5.8x(3399/585) speedups in ParquetCachedBatch write and 2.6x(370/142) speedups in ParquetCachedBatch read if we enable the rapids plugin? And if we don't enable PCBS(GpuInMemoryTableScanExec), there is no difference whether we enable rapids plugin?

Yes

**Comment by razajafri** [comment]
@nvliyuan PTAL

File: examples/pcbs-benchmark/pcbs-benchmark.sh (hunk 11 above)
Comment (razajafri) [reply examples/pcbs-benchmark/pcbs-benchmark.sh:31]: I have added the link to the tuning guide.

**Comment by nvliyuan** [comment]
> @nvliyuan PTAL

@razajafri thanks, the PR looks good to me

**Review by nvliyuan — APPROVED** [review]

**Comment by nvliyuan** [comment]
@razajafri since we just restructured the directories, I am not sure which directory this demo should belong to, I am confirming with @krajendrannv

**Comment by nvliyuan** [comment]
> 

we can put it under `SQT+DF-Examples` folder

**Comment by nvliyuan** [comment]
will close this pr and re-draft one @razajafri @sameerz
